# try:
#     raise NameError('Hola')
# except NameError:
#     print('Se ha generado un error de nombre')
# except:
#     print('Otro error')

raise NameError('Se ha generado un error en la l√≠nea 8')